import type {
  BiomeDefinition,
  DecorationDefinition,
  ItemId,
  SpeciesDefinition,
  SpeciesId,
  UpgradeDefinition,
} from "./types";
export const BIOMES: BiomeDefinition[] = [
  {
    id: "reef",
    name: "햇살 산호초",
    english: "SUNLIT REEF",
    subtitle: "빛이 머무는 바다",
    description:
      "물결 사이로 빛이 부서지는 얕은 바다. 산호의 틈에서 작은 생명과 첫 탐사의 실마리를 찾아보세요.",
    depth: "12–40 m",
    danger: 1,
    requiredSuit: 0,
    accent: "#b8e7c4",
    topColor: 0x258f9e,
    bottomColor: 0x063443,
  },
  {
    id: "wreck",
    name: "잠든 난파선",
    english: "THE SUNKEN WRECK",
    subtitle: "잊힌 항해의 흔적",
    description:
      "해초에 감싸인 오래된 선체. 끊어진 통로 너머에 심해 장비의 설계도가 잠들어 있습니다.",
    depth: "45–90 m",
    danger: 2,
    requiredSuit: 1,
    accent: "#e2c88b",
    topColor: 0x296778,
    bottomColor: 0x082a3a,
  },
  {
    id: "abyss",
    name: "푸른 잔광의 심해",
    english: "THE LUMINOUS ABYSS",
    subtitle: "어둠이 품은 빛",
    description:
      "햇빛이 닿지 않는 곳에도 빛은 있습니다. 아직 이름 붙이지 못한 경이로움이 당신을 기다립니다.",
    depth: "120–200 m",
    danger: 3,
    requiredSuit: 2,
    accent: "#a9b7f2",
    topColor: 0x243856,
    bottomColor: 0x080e24,
  },
];
export const SPECIES: SpeciesDefinition[] = [
  {
    id: "clownfish",
    name: "흰동가리",
    latin: "Amphiprion",
    biome: "reef",
    kind: "collectible",
    description:
      "산호 사이를 오가는 작은 주황빛. 가까이 다가가면 호기심 많은 눈으로 당신을 살핍니다.",
    color: "#f3a05f",
    hp: 22,
    size: 1,
  },
  {
    id: "seahorse",
    name: "해마",
    latin: "Hippocampus",
    biome: "reef",
    kind: "collectible",
    description:
      "해초에 꼬리를 걸고 물결에 몸을 맡깁니다. 서두르지 않고 다가가면 발견할 수 있습니다.",
    color: "#efca82",
    hp: 20,
    size: 0.85,
  },
  {
    id: "turtle",
    name: "바다거북",
    latin: "Chelonioidea",
    biome: "reef",
    kind: "observer",
    description:
      "느린 날갯짓으로 바다를 가로지르는 오랜 여행자. 수족관보다 넓은 바다가 어울립니다.",
    color: "#a3c6a1",
    hp: 160,
    size: 1.7,
  },
  {
    id: "crab",
    name: "갑옷 큰게",
    latin: "Brachyura · adapted",
    biome: "reef",
    kind: "predator",
    description:
      "단단한 껍질 아래 산호초의 성미 급한 수호자가 숨어 있습니다. 껍질은 내압 장비의 중요한 재료입니다.",
    color: "#d68d73",
    hp: 65,
    drop: "shell",
    size: 1.45,
  },
  {
    id: "triggerfish",
    name: "쥐치",
    latin: "Monacanthidae",
    biome: "wreck",
    kind: "collectible",
    description:
      "납작한 몸으로 난파선의 좁은 틈을 오갑니다. 꼬리의 작은 움직임만으로 방향을 바꿉니다.",
    color: "#9dcbbb",
    hp: 30,
    size: 1.15,
  },
  {
    id: "puffer",
    name: "복어",
    latin: "Tetraodontidae",
    biome: "wreck",
    kind: "collectible",
    description:
      "둥그런 몸과 작은 지느러미. 위협하지 않고 차분하게 관찰하면 있는 그대로의 모습을 보여줍니다.",
    color: "#dbd1a5",
    hp: 35,
    size: 1,
  },
  {
    id: "ray",
    name: "가오리",
    latin: "Batoidea",
    biome: "wreck",
    kind: "observer",
    description:
      "모래 위를 소리 없이 활공합니다. 오래된 배의 그림자와 함께 지나가는 모습은 한 폭의 그림 같습니다.",
    color: "#92b8c4",
    hp: 180,
    size: 2,
  },
  {
    id: "moray",
    name: "난파선 곰치",
    latin: "Muraenidae",
    biome: "wreck",
    kind: "predator",
    description:
      "선체의 어두운 틈을 지키는 날렵한 사냥꾼. 회수한 강인한 이빨로 심해 장비를 보강할 수 있습니다.",
    color: "#adbb78",
    hp: 100,
    drop: "fang",
    size: 1.8,
  },
  {
    id: "jellyfish",
    name: "발광 해파리",
    latin: "Scyphozoa · luminous",
    biome: "abyss",
    kind: "collectible",
    description:
      "천천히 펴지고 접히는 빛의 우산. 긴 촉수에 작은 별처럼 빛이 흐릅니다.",
    color: "#cab8ec",
    hp: 25,
    size: 1.2,
  },
  {
    id: "seaangel",
    name: "바다나비",
    latin: "Gymnosomata",
    biome: "abyss",
    kind: "collectible",
    description:
      "투명한 날개를 펄럭이며 어둠 속을 날아갑니다. 깊은 바다에서 만난 작은 천사 같습니다.",
    color: "#f1bea9",
    hp: 20,
    size: 0.8,
  },
  {
    id: "angler",
    name: "등불 아귀",
    latin: "Lophiiformes",
    biome: "abyss",
    kind: "predator",
    description:
      "어둠 속 작은 등불은 길잡이가 아닐 수도 있습니다. 빛보다 그 뒤의 실루엣을 먼저 살피세요.",
    color: "#8495be",
    hp: 135,
    drop: "lumen",
    size: 1.65,
  },
  {
    id: "glowray",
    name: "빛결가오리",
    latin: "Luminara pelagia · fictional",
    biome: "abyss",
    kind: "observer",
    description:
      "지느러미마다 푸른 별자리를 품은 미지의 생명. 당신의 기록으로 이 바다의 이야기에 새로운 한 페이지가 생겼습니다.",
    color: "#afeae2",
    hp: 999,
    size: 3.4,
  },
];
export const SPECIES_BY_ID = Object.fromEntries(
  SPECIES.map((s) => [s.id, s]),
) as Record<SpeciesId, SpeciesDefinition>;
export const ITEM_NAMES: Record<string, string> = {
  scrap: "인양 금속",
  mineral: "바다 광물",
  fiber: "해초 섬유",
  shell: "갑옷 껍질",
  fang: "강인한 이빨",
  lumen: "발광 결정",
  blueprintReef: "연안 장비 설계도",
  blueprintDeep: "심해 장비 설계도",
};
export function itemName(id: ItemId): string {
  return id.startsWith("specimen:")
    ? (SPECIES_BY_ID[id.slice(9) as SpeciesId]?.name ?? "생물")
    : (ITEM_NAMES[id] ?? id);
}
export const UPGRADES: UpgradeDefinition[] = [
  {
    id: "suit1",
    name: "내압복 · 연안",
    description: "45–90m 난파선 지대를 탐사할 수 있습니다.",
    category: "탐사 확장",
    costs: [
      { id: "blueprintReef", count: 1 },
      { id: "shell", count: 3 },
      { id: "scrap", count: 14 },
      { id: "fiber", count: 6 },
    ],
    icon: "suit",
  },
  {
    id: "cutter",
    name: "수중 절단기",
    description: "난파선의 막힌 통로를 열어 새로운 발견에 다가갑니다.",
    category: "새로운 도구",
    costs: [
      { id: "mineral", count: 8 },
      { id: "scrap", count: 8 },
    ],
    requires: "suit1",
    icon: "cutter",
  },
  {
    id: "suit2",
    name: "내압복 · 심해",
    description: "120–200m 발광 심해로 향하는 마지막 준비.",
    category: "탐사 확장",
    costs: [
      { id: "blueprintDeep", count: 1 },
      { id: "fang", count: 3 },
      { id: "scrap", count: 18 },
      { id: "mineral", count: 12 },
    ],
    requires: "suit1",
    icon: "suit",
  },
  {
    id: "oxygen1",
    name: "산소통 II",
    description: "산소 용량을 6분에서 7분 30초로 늘립니다.",
    category: "산소",
    costs: [
      { id: "scrap", count: 8 },
      { id: "fiber", count: 5 },
    ],
    icon: "oxygen",
  },
  {
    id: "oxygen2",
    name: "산소통 III",
    description: "산소 용량을 9분으로 늘립니다.",
    category: "산소",
    costs: [
      { id: "scrap", count: 14 },
      { id: "mineral", count: 10 },
    ],
    requires: "oxygen1",
    icon: "oxygen",
  },
  {
    id: "spear1",
    name: "작살 II",
    description: "강화된 작살로 위험 생물에 더 큰 피해를 줍니다.",
    category: "사냥",
    costs: [
      { id: "mineral", count: 8 },
      { id: "scrap", count: 6 },
    ],
    icon: "spear",
  },
  {
    id: "spear2",
    name: "작살 III",
    description: "심해 생물에 대응하는 고압 작살입니다.",
    category: "사냥",
    costs: [
      { id: "fang", count: 2 },
      { id: "mineral", count: 12 },
    ],
    requires: "spear1",
    icon: "spear",
  },
  {
    id: "cargo1",
    name: "수집 가방 II",
    description: "적재량을 32에서 48로 늘립니다.",
    category: "수집",
    costs: [
      { id: "fiber", count: 6 },
      { id: "scrap", count: 4 },
    ],
    icon: "cargo",
  },
  {
    id: "cargo2",
    name: "수집 가방 III",
    description: "적재량을 64로 늘립니다.",
    category: "수집",
    costs: [
      { id: "fiber", count: 12 },
      { id: "scrap", count: 10 },
    ],
    requires: "cargo1",
    icon: "cargo",
  },
];
export const DECORATIONS: DecorationDefinition[] = [
  {
    id: "tank",
    name: "파노라마 수족관",
    w: 4,
    h: 2,
    unlock: 0,
    description: "바다에서 데려온 생물을 전시하는 작은 세계.",
  },
  {
    id: "coralLamp",
    name: "산호 조명",
    w: 1,
    h: 1,
    unlock: 0,
    description: "따뜻한 산호색 빛을 품은 조명.",
  },
  {
    id: "shellSeat",
    name: "조개 의자",
    w: 2,
    h: 1,
    unlock: 0,
    description: "탐사 후 잠시 쉬어가는 자리.",
  },
  {
    id: "seaweedPot",
    name: "해초 화분",
    w: 1,
    h: 1,
    unlock: 1,
    description: "기지에서도 천천히 흔들리는 초록.",
  },
  {
    id: "pearlLight",
    name: "진주 램프",
    w: 1,
    h: 1,
    unlock: 2,
    description: "부드러운 진줏빛이 머무는 작은 등.",
  },
  {
    id: "shipWheel",
    name: "오래된 조타륜",
    w: 2,
    h: 1,
    unlock: 3,
    description: "잊힌 항해를 기억하는 수집품.",
  },
  {
    id: "anchor",
    name: "닻 오브제",
    w: 1,
    h: 2,
    unlock: 4,
    description: "바다와 기지를 잇는 작은 상징.",
  },
  {
    id: "modelSub",
    name: "탐사정 모형",
    w: 2,
    h: 1,
    unlock: 5,
    description: "다음 모험을 꿈꾸게 하는 모형.",
  },
  {
    id: "reefSculpture",
    name: "산호 정원",
    w: 2,
    h: 1,
    unlock: 6,
    description: "아름다운 첫 탐사의 색을 모았습니다.",
  },
  {
    id: "starMobile",
    name: "별빛 모빌",
    w: 1,
    h: 1,
    unlock: 7,
    description: "천천히 회전하는 바다의 별들.",
  },
  {
    id: "abyssCrystal",
    name: "심해 결정등",
    w: 1,
    h: 1,
    unlock: 9,
    description: "어둠에서 가져온 푸른 빛.",
  },
  {
    id: "discoveryTrophy",
    name: "빛결의 기록",
    w: 2,
    h: 1,
    unlock: 12,
    description: "미지의 바다에 닿은 탐험가의 기념품.",
  },
];
export const TOOLS = [
  {
    id: "scanner",
    name: "스캐너",
    key: "1",
    hint: "가까운 생물을 조준해 길게 스캔",
  },
  { id: "net", name: "채집망", key: "2", hint: "작은 생물을 가까이에서 채집" },
  { id: "spear", name: "작살", key: "3", hint: "위험 생물을 조준해 발사" },
  {
    id: "cutter",
    name: "절단기",
    key: "4",
    hint: "막힌 통로 가까이에서 길게 사용",
  },
] as const;
export const GRID = { width: 12, height: 6 };
